server:
  servlet:
    context-path: /Eureka
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 2097152
  port: 6420
spring:
  datasource:
    url: jdbc:mysql://wangyujie.top:3306/Eureka?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: wyj
    password: 051564200515Wyj
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main
      exclude: static/jar/**
  redis:
    host: 175.24.22.161
    port: 6379
    database: 0
    timeout: 5000
    password: 642005
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
mybatis:
  mapper-locations: classpath:mappers/*.xml
